import { NextRequest, NextResponse } from "next/server";
import { supabaseAdmin } from "@/app/lib/supabaseServer";
import fs from 'fs';
import path from 'path';

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { email } = body;

    // Validate email
    if (!email || !email.includes('@')) {
      return NextResponse.json(
        { error: "Valid email address is required." },
        { status: 400 }
      );
    }

    // Get client IP and user agent for analytics
    const ipAddress = req.headers.get('x-forwarded-for')?.split(',')[0] || 
                      req.headers.get('x-real-ip') || 
                      'unknown';
    const userAgent = req.headers.get('user-agent') || 'unknown';

    // Store the email in database
    const { error: dbError } = await supabaseAdmin
      .from('ebook_downloads')
      .insert([
        {
          email: email.toLowerCase().trim(),
          ip_address: ipAddress,
          user_agent: userAgent,
        },
      ]);

    if (dbError) {
      console.error('Error saving ebook download:', dbError);
      // Don't fail the download if database insert fails - still allow download
    }

    // Read the markdown file
    const filePath = path.join(process.cwd(), 'public', 'blogs', 'how-to-rank-on-chatgpt-openai-seo-guide.md');
    
    if (!fs.existsSync(filePath)) {
      return NextResponse.json(
        { error: "Ebook file not found" },
        { status: 404 }
      );
    }

    const markdownContent = fs.readFileSync(filePath, 'utf-8');

    // Convert markdown to a readable text format for download
    // Remove markdown syntax to make it more readable as plain text
    let ebookContent = markdownContent
      // Remove code blocks but keep content
      .replace(/```[\s\S]*?```/g, '')
      // Remove inline code
      .replace(/`([^`]+)`/g, '$1')
      // Convert headers
      .replace(/^# (.+)$/gm, '$1\n' + '='.repeat(50) + '\n')
      .replace(/^## (.+)$/gm, '\n$1\n' + '-'.repeat(50) + '\n')
      .replace(/^### (.+)$/gm, '\n$1:\n')
      // Convert lists
      .replace(/^\- (.+)$/gm, '• $1')
      .replace(/^\d+\. (.+)$/gm, '$1')
      // Remove markdown links but keep text
      .replace(/\[([^\]]+)\]\([^\)]+\)/g, '$1')
      // Clean up extra whitespace
      .replace(/\n{3,}/g, '\n\n')
      .trim();

    // Add header and footer
    const fullEbook = `Complete Guide: How to Rank Your Website on ChatGPT & OpenAI Search
============================================================

Generated from: https://www.kommi.in
Downloaded by: ${email}
Date: ${new Date().toLocaleDateString()}

============================================================

${ebookContent}

============================================================

This ebook was generated by kommi - Track and improve your brand's visibility in AI answers.

Visit https://www.kommi.in to start tracking your ChatGPT mentions today.

© 2025 kommi. All rights reserved.
`;

    // Return as downloadable file
    return new NextResponse(fullEbook, {
      status: 200,
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Content-Disposition': `attachment; filename="how-to-rank-on-chatgpt-ebook.txt"`,
        'Content-Length': Buffer.byteLength(fullEbook, 'utf-8').toString(),
      },
    });
  } catch (error: any) {
    console.error('Ebook download error:', error);
    return NextResponse.json(
      { error: "Failed to generate ebook. Please try again." },
      { status: 500 }
    );
  }
}

